web01/web01/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'web01.views.home', name='home'),
    # url(r'^web01/', include('web01.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$','blog.views.index'),
    url(r'^regist/$','blog.views.regist_user'),
    url(r'^login/$','blog.views.login_user'),
    url(r'^type/$','blog.views.disp_goods'),
    url(r'^buy_goods/$','blog.views.buy_goods'),
    #url(r'^logout/$','blog.views.logout_user'),
    url(r'^order/$','blog.views.order'),
    url(r'^pay/$','blog.views.pay'),
)

web01/blog/models.py
#-*coding:utf8
from django.db import models
from django.contrib.auth.models import User

class ProUser(models.Model):
    user = models.OneToOneField(User)
    tel = models.CharField(max_length=20,verbose_name=u'联系方式')
    addr = models.CharField(max_length=50,verbose_name=u'派送地址')
    QQ  = models.CharField(max_length=15,null=True,blank=True,verbose_name=u'QQ')

class Goods(models.Model):
    name       = models.CharField(max_length=20)
    price      = models.FloatField() 
    img        = models.FileField(upload_to="./goodsImg/") 
    category   = models.ForeignKey("Category") 
    def __unicode__(self):
        return self.name

class Category(models.Model):
    category_name = models.CharField(max_length=20)
    p_category    = models.ForeignKey("self",null=True,blank=True)
    def __unicode__(self):
        return self.category_name

class LineItem(models.Model):  
    goods       = models.ForeignKey(Goods)  
    goods_price = models.FloatField()  
    quantity    = models.IntegerField() 
    def __unicode__(self):
        return self.goods 





'''
class ShopCar(models.Model):
    user = models.OneToOneField(User)
    goods = models.ManyToManyField(Goods)
    def __unicode__(self):
        return self.user
    
    def add_goods(self):
        pass

    def remove_goods(self):
        pass

    def update_goods(self):
        pass

'''

web01/blog/views.py
#-*coding:utf8
from django.http import HttpResponse
from django.shortcuts import render_to_response,render
from blog.models import ProUser,Goods,Category,LineItem
from django.contrib.auth import authenticate,login
from django.contrib.auth.models import User
from django import forms
from django.http import HttpResponseRedirect
import json

class RegistUserForm(forms.ModelForm):
    username = forms.CharField(label=u'用户名')
    password = forms.CharField(label=u'口令',widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username','password') 

class RegistProUserForm(forms.ModelForm):
    class Meta:
        model = ProUser
        fields = ('tel','addr','QQ')

def index(req):
    goodlist = req.session.get('goodlist')

    goods_list    = Goods.objects.all()
    category_list = Category.objects.all() 
    categorys     = [category for category in category_list if category.p_category is None]
    if req.user.is_authenticated():
        return render(req,"index.html",{'user':req.user,'goods_list':goods_list,'categorys':categorys, 'goodlist':goodlist})
    else:
        return render(req,"index.html",{'goods_list':goods_list,'categorys':categorys, 'goodlist':goodlist})

def regist_user(req):
    if req.method == "POST":
        rf1 = RegistUserForm(req.POST)
        rf2 = RegistProUserForm(req.POST)
        if rf1.is_valid() and rf2.is_valid():
            rf1.instance.is_staff = True
            rf1.instance.set_password(rf1.cleaned_data['password'])
            rf1.save()
            rf2.instance.user = rf1.instance 
            rf2.save()
            return HttpResponse("<h2>亲,你已经注册成功了哦!<br />到首页<b>登寻</b>找宝贝去吧~~</h2>")
    else:
        rf1 = RegistUserForm()
        rf2 = RegistProUserForm()
    return render(req,'regist.html',{'rf1':rf1,'rf2':rf2})
    
def login_user(req):
    username = req.POST.get('username')
    password = req.POST.get('password')
    user = authenticate(username=username,password=password)
    if user is not None:
        #print user.username 
        login(req,user)
        return HttpResponse(username)
    else:
        return HttpResponseRedirect('/index/')

def disp_goods(req):
    goods_list    = Goods.objects.all()
    category_list = Category.objects.all() 
    categorys     = [category for category in category_list if category.p_category is None]
    type_id       = req.GET.get("type_id")
    goods_type    = Category.objects.get(id=type_id) 
    goods_list    = goods_type.goods_set.all()
    return render(req,"index.html",{'goods_list':goods_list,'categorys':categorys,'goods_list':goods_list})

def buy_goods(req):
    goodlist = req.POST.get("goodlist")
    #print goodlist
    exec "goodlist = %s"%goodlist
    #goodlist = json.loads(goodlist)
    #print type(goodlist)
    #print goodlist
    req.session['goodlist'] = goodlist
    return HttpResponse("ok")











'''
class ShopCar(object):  
    def __init__(self, *args, **kwargs):  
        self.items = []  
        self.total_price = 0  
    def add_product(self,product):  
        self.total_price += goods.price  
        for item in self.items:  
            if item.goods.id == goods.id:  
                item.quantity += 1   
                return  
        self.items.append(LineItem(product=product,goods_price=goods.price,quantity=1))

def order(req):
    return render_to_response("order.html",{})
def pay(req):
    return render_to_response("pay.html",{})



def logout_user(req):
    pass
    '''

web01/blog/templates/disp_goods.html
<!DOCTYPE html><!-- saved from url=(0064)http://docs.bootcss.com/bootstrap-2.3.2/docs/examples/fluid.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>爱尚品--你的加入，生活更加美妙！</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le styles -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="/static/bootstrap/js/bootstrap.js"></script>
    <script src="/static/bootstrap/js/jquery.js" type="text/javascript"></script>
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
		background-color:#FCC;
      }
	  .hero-unit{
	   background-color:#FCC;		
	  }
      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          padding-left: 5px;
          padding-right: 5px;
        }
      }
	  img{
	  	width:250px;
		height:300px;
	  }
	  .thumbnail{
		width:278px;
		height:450px;
		margin:10px;
	  }
        #myModal{
            width:400px;
            height:300px;
            display:none;
            background-color:green;
            position:absolute;
            top:200px;
            left:450px;
        }

      #car{
        position:fixed; 
        border:5px #F96 dotted;       
        width:250px;
        height:450px;
        margin:10px 20px;
     }


    </style>

    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

      <link rel="shortcut icon" href="/static/bootstrap/img/glyphicons-halflings.png">
      <link rel="shortcut icon" href="/static/bootstrap/img/glyphicons-halflings-white.png">
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#" title="爱尚品--你的加入,生活更加美妙!">爱尚品</a>
          <div class="nav-collapse collapse">
            <span class="navbar-text pull-right btn-group">
               <div id="login_msg" style="font-size:16px;">
               {% if user.is_authenticated %}
               <p class='nav'>亲爱的{{user.username}}童鞋,好久不见哦!</p>
               {% else %}
				    <button class="btn" onclick="regist()" target="#">注册</button>
				    <button class="btn" onclick="toDisplay()" data-target="#myModal" data-toggle="modal" >登录</button>
                {% endif %}
               </div>
                    <script>
                        function regist(){
                            open("/regist/");    
                        }
                        function toDisplay(){
                            var modal = document.getElementById('myModal');
                            modal.style.display='block';
                        }
                    </script>
            </span>
            <ul class="nav">
              <li><a href="#">首页</a></li>
              <li class="active" title="亲,挑选你喜欢的放入口袋吧!"><a href="#about">开始订购</a></li>
              <li><a href="#contact">查询订单</a></li>
              <li><a href="#contact">手机客户端</a></li>
              <li><a href="#contact">帮助中心</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--div class="container-fluid"结束  -->
      </div><!--div class="navbar-inner"结束 -->
    </div><!-- div class="navbar navbar-fixed-top"-->
                <!--div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"-->
                <div id="myModal">
                    <form onsubmit="login(); return false;">{%csrf_token%}
                    <table class="table modal-body">
                        <tr><td>用户名</td></tr>
                        <tr><td><input type="text" name="username" id="username" /></td></tr>
                        <tr><td>密码</td></tr>
                        <tr><td><input type="password" name="password" id="password" /></td></tr>
                    </table>
                    <button class="btn btn-primary">登陆</button>
                    </form>
                    <button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
                </div>

<div>
    <script type="text/javascript" >
        var hr = new XMLHttpRequest();
        function login(){
            hr.open('post','/login/',true);
            hr.setRequestHeader("Content-type","application/x-www-form-urlencoded");
            hr.onreadystatechange = process;
            var username = document.getElementById('username').value;
            var password = document.getElementById('password').value;
            hr.send('username='+username+'&password='+password);
        }
        function process(){
            if(hr.readyState == 4 && hr.status == 200){
                if(hr.responseText != ''){
                    var login_msg = document.getElementById('login_msg');
                    login_msg.innerHTML = '亲爱的'+hr.responseText+'童鞋,好久不见!';
                }
            }
        }
    </script>
</div>

      <div class="row-fluid">    
          <div class="span2 ">
                  <div id="list" style="position:fixed">
                  <ul class="nav nav-list " >
                      <li class="nav-header">优惠直通车</li>
                      <li><a href="#">本日特惠</a></li>
                      <li><a href="#">新品推介</a></li>
                      <li><a href="#">团购进行中</a></li>
                      {%for category in categorys%}
                        <li class="nav-header"><a href="#">{{category.category_name}}</a></li>
                        {%for type in category.category_set.all%}
                            <li><a href="/type/?type_id={{type.id}}">{{type.category_name}}</a></li>
                        {%endfor%}
                      {%endfor%}
                  </ul>
                  </div><!-- id= /list-->
          </div><!--.span2-->
          
          <div class="span7">
            <div class="row-fuid">
            {%for goods in goods_list%}
               <div class=span4>
                   <div class="thumbnail">
                       <img src="/static/{{goods.img}}" alt="img" />
                       <h3 goods_name="{{goods.name}}">{{goods.name}}</h3>
                       <h4 goods_price="{{tea.price}}">{{goods.price}}元</h4>
                       <button class="btn" goods_id="{{goods.id}}">加入购物车 &raquo;</button>
                   </div><!--/thumbnail-->
               </div><!--/span4-->
                 {%if forloop.counter|divisibleby:3%}
            </div><div class="row-fluid">
                 {%else%}
                 {%endif%}
            {%endfor%}
            </div>
            </div><!--.span8-->
         
             <script type="text/javascript">
                 var goodlist = new Array();  //生成一个数组
                 function disp_goods(){
                     var car = $("#shop_car");
                     car.text('');
                     for(var i=0; i<=goodlist.length-1;i++){
                         //alert(goodlist[i].goods_name);
                        $(car).append("<tr><td>"+goodlist[i].goods_name+"</td><td>"+goodlist[i].goods_price+"</td></tr>");
                     }
                 }
                 $(document).ready(function(){
                    $(".btn").click(function(){
                        var JSONObject = {
                        "goods_id": $(this).attr("goods_id"),
                        "goods_name": $(this).siblings("h3").html(),
                        "goods_price": $(this).siblings("h4").html(),
                        };
                        //alert(goods_name);
                        goodlist.push(JSONObject);
                        disp_goods();
                        
                    })    
                 })
             </script>

      	  <div class="span3 ">
             <div id="car"><!--购物车开始 -->
               {% block title %} 我的购物车 {% endblock %}
               {% block content %}
                    <table class="table table-condensed">
                        <thead>
                            <tr>
                                <th class="header">品名</th class="yellow header"><th>数量</th><th>价格</th><th>取消</th>
                            </tr>
                        </thead>
                        <tbody class="tbody table-hover" id="shop_car">
                            <tr> </tr>
                            <tr> </tr><hr />
                            <tr><th>小计：</th><td></td></tr> 
                            <tr><th>外送费：</th><td></td></tr>
                            <tr><th>合计：</th><td></td></tr>            
                        </tbody>
                    </table>
                    <div id="order_footer">
                       <button class="btn" onclick="ToOrder()">进入结算 &raquo</button>
                       <div>提醒：根据你最终提交订单时间，送达时间可能略有调整。</div> 
                    </div>
               {% endblock %}
               <script>
                    function ToOrder(){
                       location.assign("/order/");
                    }
               </script>
      		 </div><!--购物车结束 -->
          </div><!--/.span3 112行-->
      </div><!--.row-fluid-->
          
        
      

      <hr>
      <footer>
        <p>&copy; Company 2013</p>
      </footer>

  
  </body>
</html>

web01/blog/templates/index.html
<!DOCTYPE html><!-- saved from url=(0064)http://docs.bootcss.com/bootstrap-2.3.2/docs/examples/fluid.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>爱尚品--你的加入，生活更加美妙！</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le styles -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="/static/bootstrap/js/bootstrap.js"></script>
    <script src="/static/bootstrap/js/jquery.js" type="text/javascript"></script>
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
		background-color:#FCC;
      }
	  .hero-unit{
	   background-color:#FCC;		
	  }
      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          padding-left: 5px;
          padding-right: 5px;
        }
      }
	  img{
	  	width:250px;
		height:300px;
	  }
	  .thumbnail{
		width:278px;
		height:450px;
		margin:10px;
	  }
        #myModal{
            width:400px;
            height:300px;
            display:none;
            background-color:green;
            position:absolute;
            top:200px;
            left:450px;
        }

      #car{
        position:fixed; 
        border:5px #F96 dotted;       
        border-radius:5px;
        width:250px;
        height:450px;
        margin:10px 20px;
     }


    </style>

    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

      <link rel="shortcut icon" href="/static/bootstrap/img/glyphicons-halflings.png">
      <link rel="shortcut icon" href="/static/bootstrap/img/glyphicons-halflings-white.png">

      <script type="text/javascript">
         $(document).ready(function(){
             function contains(a,obj){
                 for(var i=0; i<a.length; i++){
                     if(a[i].goods_id == obj.goods_id)
                         return true;
                 }
                 return false;
             }

             function Add_Quantity(a,obj){
                 for(var i=0; i<a.length; i++){
                     if(a[i].goods_id == obj.goods_id)
                         a[i].goods_quantity ++;
                 }
             }

             function disp_goods(){
                 var car = $("#shop_car");
                 car.text('');
                 for(var i=0; i<goodlist.length;i++){
                    $(car).append("<tr><td>"+goodlist[i].goods_name+"</td><td><i class='icon-plus'></i> "+goodlist[i].goods_quantity+" <i class='icon-minus'></i></td><td>"+goodlist[i].goods_price+"</td><td><i class='icon-remove'></i></td></tr>");
                    }
             }   

             var goodlist = new Array();  //生成一个数组
             $(".btn").click(function(){
                 var JSONObject = {
                 "goods_id": $(this).attr("goods_id"),
                 "goods_name": $(this).siblings("h3").html(),
                 "goods_price": $(this).siblings("h4").html(),
                 "goods_quantity": 1
                 };
                 if (contains(goodlist,JSONObject)){
                     Add_Quantity(goodlist,JSONObject);
                 }else{
                     goodlist.push(JSONObject);
                 }
                  $.post("/buy_goods/",{"goodlist":JSON.stringify(goodlist)});
                 disp_goods();
             });    
          });
      </script>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#" title="爱尚品--你的加入,生活更加美妙!">爱尚品</a>
          <div class="nav-collapse collapse">
            <span class="navbar-text pull-right btn-group">
               <div id="login_msg" style="font-size:16px;">
               {% if user.is_authenticated %}
               <p class='nav'>亲爱的{{user.username}}童鞋,好久不见哦!</p>
               {% else %}
				    <button class="btn" onclick="regist()" target="#">注册</button>
				    <button class="btn" onclick="toDisplay()" data-target="#myModal" data-toggle="modal" >登录</button>
                {% endif %}
               </div>
                    <script>
                        function regist(){
                            open("/regist/");    
                        }
                        function toDisplay(){
                            var modal = document.getElementById('myModal');
                            modal.style.display='block';
                        }
                    </script>
            </span>
            <ul class="nav">
              <li><a href="#">首页</a></li>
              <li class="active" title="亲,挑选你喜欢的放入口袋吧!"><a href="#about">开始订购</a></li>
              <li><a href="#contact">查询订单</a></li>
              <li><a href="#contact">手机客户端</a></li>
              <li><a href="#contact">帮助中心</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--div class="container-fluid"结束  -->
      </div><!--div class="navbar-inner"结束 -->
    </div><!-- div class="navbar navbar-fixed-top"-->
                <!--div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"-->
                <div id="myModal">
                    <form onsubmit="login(); return false;">{%csrf_token%}
                    <table class="table modal-body">
                        <tr><td>用户名</td></tr>
                        <tr><td><input type="text" name="username" id="username" /></td></tr>
                        <tr><td>密码</td></tr>
                        <tr><td><input type="password" name="password" id="password" /></td></tr>
                    </table>
                    <button class="btn btn-primary">登陆</button>
                    </form>
                    <button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
                </div>

<div>
    <script type="text/javascript" >
        var hr = new XMLHttpRequest();
        function login(){
            hr.open('post','/login/',true);
            hr.setRequestHeader("Content-type","application/x-www-form-urlencoded");
            hr.onreadystatechange = process;
            var username = document.getElementById('username').value;
            var password = document.getElementById('password').value;
            hr.send('username='+username+'&password='+password);
        }
        function process(){
            if(hr.readyState == 4 && hr.status == 200){
                if(hr.responseText != ''){
                    var login_msg = document.getElementById('login_msg');
                    login_msg.innerHTML = '亲爱的'+hr.responseText+'童鞋,好久不见!';
                }
            }
        }
    </script>
</div>

      <div class="row-fluid">    
          <div class="span2 ">
                  <div id="list" style="position:fixed">
                  <ul class="nav nav-list " >
                      <li class="nav-header">优惠直通车</li>
                      <li><a href="#">本日特惠</a></li>
                      <li><a href="#">新品推介</a></li>
                      <li><a href="#">团购进行中</a></li>
                      {%for category in categorys%}
                        <li class="nav-header">{{category.category_name}}</li>
                        {%for type in category.category_set.all%}
                            <li><a href="/type/?type_id={{type.id}}">{{type.category_name}}</a></li>
                        {%endfor%}
                      {%endfor%}
                  </ul>
                  </div><!-- id= /list-->
          </div><!--.span2-->
          
          <div class="span7">
            <div class="row-fuid">
            {%for goods in goods_list%}
               <div class=span4>
                   <div class="thumbnail">
                       <img src="/static/{{goods.img}}" alt="img" />
                       <h3 goods_name="{{goods.name}}">{{goods.name}}</h3>
                       <h4 goods_price="{{tea.price}}">￥{{goods.price|floatformat:"2"}}</h4>
                       <button goods_id="{{goods.id}}" class="btn" >加入购物车 &raquo;</button>
                   </div><!--/thumbnail-->
               </div><!--/span4-->
                 {%if forloop.counter|divisibleby:3%}
            </div><div class="row-fluid">
                 {%else%}
                 {%endif%}
            {%endfor%}
            </div>
            </div><!--.span8-->
         

      	  <div class="span3 ">
             <div id="car"><!--购物车开始 -->
               {% block title %} 我的购物车 {% endblock %}
               {% block content %}
               {{goodlist}}
                    <table class="table table-condensed">
                        <thead>
                            <tr>
                                <th class="header">品名</th class="yellow header"><th>数量</th><th>价格</th><th>取消</th>
                            </tr>
                        </thead>
                        <tbody class="tbody table-hover" id="shop_car">
                            <tr> </tr>
                            <tr> </tr><hr />
                            <tr><th>小计：</th><td></td></tr> 
                            <tr><th>外送费：</th><td></td></tr>
                            <tr><th>合计：</th><td></td></tr>            
                        </tbody>
                    </table>
                    <div id="order_footer">
                       <button class="btn" onclick="ToOrder()">进入结算 &raquo</button>
                       <div>提醒：根据你最终提交订单时间，送达时间可能略有调整。</div> 
                    </div>
               {% endblock %}
               <script>
                    function ToOrder(){
                       location.assign("/order/");
                    }
               </script>
      		 </div><!--购物车结束 -->
          </div><!--/.span3 112行-->
      </div><!--.row-fluid-->
          
        
      

      <hr>
      <footer>
        <p>&copy; Company 2013</p>
      </footer>

  
  </body>
</html>

web01/blog/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>爱尚品--你的加入，生活多一份美妙！</title>
<style>
	body{
		
		background-image:url(/static/images/tea5.jpg);

	}
	#main{
		position:absolute;
		left:560px;
		top:185px;
		font-size:24px;
		font-family:cursive, Comic Sans MS, Zapf Chancery, Author;
	}
	
</style>
</head>

<body>
	<div id="main">
    	<h3><span>用户登录</span></h3>
        <form>
            <table>
                <tr><td>用户名</td><td><input type="text" name="username" /></td></tr>
                <tr><td>密码</td><td><input type="password" name="password" /></td></tr>
            </table>
            <span><input type="button"  value="登录"/></span>
        </form>
    </div>

</body>
</html>

web01/blog/templates/regist.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>爱尚品--你的加入，生活多一份美妙！</title>
	<style>
    	div,ul,li,a,body,table,tr,td{
			margin:opx;	
		}
		body{
			width:100%;
			background-image:url(/static/images/tea7.jpg);
			background-color:#F93;	
			font-size:20px;
			font-family:Georgia, "Times New Roman", Times, serif;
			color:#991;
		}
		
		#header{
			position:absolute;
			left:1100px;
		}
		a{
			 text-decoration:none;
		}
		#main{
			position:fixed;
			margin:0 auto;
			left:560px;
			top:185px;
			width:400px;
			height:600px;
		}
		
		
		
    </style>
</head>

<body>
	<div id="header">
		<a href="#" title="我的爱尚品（is通行证）" style="color:#999;">我的爱尚品（is通行证）</a> 
       	<input type="button" value="登录" />   	
    </div>
    <div id="main">
    	<form action="" method="post">{%csrf_token%}
        <span style="color:#666">***一分钟，完成注册！***</span>
            <table>
                {{rf1.as_table}}
                {{rf2.as_table}}
            </table>                
            <span style="font-size:16px;">(此项用于送出礼品，为选填信息)</span><br />
            <input type="submit" value="确认提交" />
        </form>
    </div>

</body>
</html>